version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: currency_task_database
    restart: always
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'